### ISSUE TITLE
When making flows app crashes

### ISSUE THREAD

**Issue by mruiter** [athombv/com.mipow.playbulb#1]
TypeError: Cannot read property 'slice' of undefined
at Function.state2buffer (/drivers/driver.js:402:31)
at /drivers/driver.js:318:19
at /homey-app/wireless/ble.js:35:12
at process.<anonymous> (/homey-app/helpers/client.js:1:1269)
at emitTwo (events.js:87:13)
at process.emit (events.js:172:7)
at internal/child_process.js:696:12
at nextTickCallbackWith0Args (node.js:420:9)
at process._tickCallback (node.js:349:13)

Exit code: 1
Exit signal: null

**Comment by jjtbsomhorst** [comment]
Any update on this?

**Comment by mruiter** [comment]
fixed but still open so ill close it
